version: 0.0.1.{build}

clone_depth: 1

environment:
  MAKEFLAGS: -j4

cache:
  - .stack-work
  - asterius\.stack-work
  - binaryen\.stack-work
  - genapply\.stack-work
  - ghc-toolkit\.stack-work

build_script:
  - git submodule update --init --recursive
  - choco install haskell-stack nodejs
  - stack --no-terminal --skip-msys setup > NUL
  - mklink /D %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025 C:\\msys64
  - copy %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\ghc-8.5.*.installed %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025.installed
  - stack --no-terminal exec pacman -- -S autoconf coreutils make mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc --needed --noconfirm --noprogressbar
  - stack --no-terminal build --haddock --test --no-run-tests
  - stack --no-terminal exec ahc-boot
  - stack --no-terminal test asterius:fib

test: off
