version: 0.0.1.{build}

shallow_clone: true

cache:
  - .stack-work
  - genapply\.stack-work
  - ghc-toolkit\.stack-work

environment:
  MAKEFLAGS: -j4

build_script:
  - choco install haskell-stack
  - ps: Install-Product node Current x64
  - stack --no-terminal --skip-msys setup > NUL
  - mklink /D %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025 C:\\msys64
  - copy %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\ghc-8.7.*.installed %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025.installed
  - stack --no-terminal exec pacman -- -S autoconf coreutils make mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc --needed --noconfirm --noprogressbar
  - stack --no-terminal build --haddock --test --no-run-tests
  - stack --no-terminal exec ahc-boot
  - stack --no-terminal exec ahc-boot -- --rts-only
  - stack --no-terminal test asterius:fib --test-arguments="--debug"
  - stack --no-terminal test asterius:fib --test-arguments="--optimize"
  - stack --no-terminal test asterius:jsffi --test-arguments="--debug"
  - stack --no-terminal test asterius:jsffi --test-arguments="--optimize"
  - stack --no-terminal test asterius:array --test-arguments="--debug"
  - stack --no-terminal test asterius:array --test-arguments="--optimize"
  - stack --no-terminal test asterius:stableptr --test-arguments="--debug"
  - stack --no-terminal test asterius:stableptr --test-arguments="--optimize"
  - stack --no-terminal test asterius:rtsapi --test-arguments="--debug"
  - stack --no-terminal test asterius:rtsapi --test-arguments="--optimize"

test: off
