site_name: Asterius
site_url: https://tweag.github.io/asterius
repo_url: https://github.com/tweag/asterius
pages:
  - 'Home': 'index.md'
  - 'Building guide': 'building.md'
  - 'Cabal support': 'cabal.md'
  - 'Using ahc-dist/ahc-link': 'ahc-link.md'
  - 'JavaScript FFI': 'jsffi.md'
  - 'The Vault': 'vault.md'
  - 'Invoking RTS API in JavaScript': 'rts-api.md'
  - 'IR types and transformation passes': 'ir.md'
  - 'The runtime debugging feature': 'debugging.md'
  - 'Project architecture': 'architecture.md'
  - 'Writing WebAssembly code in Haskell': 'wasm-in-hs.md'
  - 'WebAssembly as a Haskell compilation target': 'webassembly.md'
  - 'About the custom GHC fork': 'custom-ghc.md'
  - 'Reading list': 'readings.md'
  - 'Status reports': 'reports.md'
theme: readthedocs
