sudo: required
env:
- GHCVER=7.4
- GHCVER=7.6
- GHCVER=7.8
- GHCVER=7.10
- GHCVER=8.0
- GHCVER=8.2
- GHCVER=8.4
- GHCVER=8.6
- GHCVER=head

script:
- curl -sSL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh
